In [5]:
# !pip install python-dotenv
import os
from dotenv import load_dotenv
load_dotenv()

DB_NAME = os.getenv("DB_NAME")
DB_USER = os.getenv("DB_USER")
DB_PASSWORD = os.getenv("DB_PASSWORD")
DB_HOSTNAME = os.getenv("DB_HOSTNAME")

%load_ext sql

The sql extension is already loaded. To reload it, use:
  %reload_ext sql

In [6]:
%sql postgresql://$DB_USER:$DB_PASSWORD@$DB_HOSTNAME/$DB_NAME

#### List data in table DimDate

In [7]:
%sql SELECT * FROM dimdate LIMIT 5;

 * postgresql://postgres:***@localhost/sales
5 rows affected.

[(1, datetime.date(2019, 1, 1), 2019, 1, 'Q1', 1, 'January', 1, 3, 'Tuesday'),
 (2, datetime.date(2019, 1, 2), 2019, 1, 'Q1', 1, 'January', 2, 4, 'Wednesday'),
 (3, datetime.date(2019, 1, 3), 2019, 1, 'Q1', 1, 'January', 3, 5, 'Thursday'),
 (4, datetime.date(2019, 1, 4), 2019, 1, 'Q1', 1, 'January', 4, 6, 'Friday'),
 (5, datetime.date(2019, 1, 5), 2019, 1, 'Q1', 1, 'January', 5, 7, 'Saturday')]

#### List data in table DimCategory

In [8]:
%sql SELECT * FROM dimcategory LIMIT 5;

 * postgresql://postgres:***@localhost/sales
5 rows affected.

[(1, 'Electronics'), (2, 'Books'), (3, 'Toys'), (4, 'Sports'), (5, 'Software')]

#### List data in table DimCountry

In [9]:
%sql SELECT * FROM dimcountry LIMIT 5;

 * postgresql://postgres:***@localhost/sales
5 rows affected.

[(1, 'Argentina'),
 (2, 'Australia'),
 (3, 'Austria'),
 (4, 'Azerbaijan'),
 (5, 'Belgium')]

#### List data in table FactSales

In [10]:
%sql SELECT * FROM factsales LIMIT 5;

 * postgresql://postgres:***@localhost/sales
5 rows affected.

[(1, 1, 6, 4, 5190),
 (2, 1, 25, 2, 1205),
 (3, 1, 22, 5, 3155),
 (4, 1, 40, 2, 268),
 (5, 1, 28, 3, 3199)]

##### Create a grouping sets query using the columns country, category, totalsales.

In [21]:
%sql SELECT dimcountry.country,dimcategory.category, SUM(factsales.amount) AS totalsales\
    FROM dimcountry\
    INNER JOIN factsales\
    ON dimcountry.country_id = factsales.country_id\
    INNER JOIN dimcategory\
    ON dimcategory.category_id = factsales.category_id\
    GROUP BY GROUPING SETS(dimcountry.country, dimcategory.category)\
    ORDER BY dimcountry.country, dimcategory.category

 * postgresql://postgres:***@localhost/sales
61 rows affected.

[('Argentina', None, 21755581),
 ('Australia', None, 21522004),
 ('Austria', None, 21365726),
 ('Azerbaijan', None, 21325766),
 ('Belgium', None, 21498249),
 ('Brazil', None, 21350771),
 ('Bulgaria', None, 21410716),
 ('Canada', None, 21575438),
 ('Cyprus', None, 21500526),
 ('Czech Republic', None, 21334142),
 ('Denmark', None, 21331097),
 ('Egypt', None, 21379967),
 ('Estonia', None, 21493054),
 ('Finland', None, 21336188),
 ('France', None, 21341055),
 ('Germany', None, 21301931),
 ('Greece', None, 21412393),
 ('Hungary', None, 21338015),
 ('India', None, 21330883),
 ('Indonesia', None, 21498960),
 ('Ireland', None, 21095982),
 ('Israel', None, 21581548),
 ('Italy', None, 21844913),
 ('Japan', None, 21765341),
 ('Jordan', None, 21429604),
 ('Malaysia', None, 21452597),
 ('Mexico', None, 21455404),
 ('Netherlands', None, 21383019),
 ('New Zealand', None, 21329461),
 ('Norway', None, 21544439),
 ('Oman', None, 21433121),
 ('Peru', None, 21704462),
 ('Philippines', None, 21651762),
 ('Poland', None, 21845131),
 ('Portugal', None, 21554611),
 ('Qatar', None, 21473762),
 ('Russia', None, 21738876),
 ('Saudi Arabia', None, 21326437),
 ('Singapore', None, 21534966),
 ('South Africa', None, 21394755),
 ('South Korea', None, 21598368),
 ('Spain', None, 21465342),
 ('Sudan', None, 21415934),
 ('Sweden', None, 21000525),
 ('Switzerland', None, 21526097),
 ('Taiwan', None, 21060208),
 ('Tajikistan', None, 21517513),
 ('Thailand', None, 21848776),
 ('Turkey', None, 21270737),
 ('Ukraine', None, 21474740),
 ('United Arab Emirates', None, 21444221),
 ('United Kingdom', None, 21415113),
 ('United States', None, 21007997),
 ('Uruguay', None, 21321382),
 ('Uzbekistan', None, 21416080),
 ('Vietnam', None, 21280572),
 (None, 'Books', 239357597),
 (None, 'Electronics', 239912568),
 (None, 'Software', 240289802),
 (None, 'Sports', 240709913),
 (None, 'Toys', 240736378)]

##### Create a rollup query using the columns year, country, and totalsales

In [23]:
%sql SELECT dimcountry.country,dimdate.year, SUM(factsales.amount) AS totalsales\
    FROM dimcountry\
    INNER JOIN factsales\
    ON dimcountry.country_id = factsales.country_id\
    INNER JOIN dimdate\
    ON dimdate.date_id = factsales.date_id\
    GROUP BY ROLLUP(dimcountry.country, dimdate.year)\
    ORDER BY dimcountry.country, dimdate.year

 * postgresql://postgres:***@localhost/sales
225 rows affected.

[('Argentina', 2019, 7163167),
 ('Argentina', 2020, 7327655),
 ('Argentina', 2021, 7264759),
 ('Argentina', None, 21755581),
 ('Australia', 2019, 7259016),
 ('Australia', 2020, 6964260),
 ('Australia', 2021, 7298728),
 ('Australia', None, 21522004),
 ('Austria', 2019, 7320233),
 ('Austria', 2020, 7071166),
 ('Austria', 2021, 6974327),
 ('Austria', None, 21365726),
 ('Azerbaijan', 2019, 7097729),
 ('Azerbaijan', 2020, 7191956),
 ('Azerbaijan', 2021, 7036081),
 ('Azerbaijan', None, 21325766),
 ('Belgium', 2019, 7093441),
 ('Belgium', 2020, 7070520),
 ('Belgium', 2021, 7334288),
 ('Belgium', None, 21498249),
 ('Brazil', 2019, 7116253),
 ('Brazil', 2020, 7087658),
 ('Brazil', 2021, 7146860),
 ('Brazil', None, 21350771),
 ('Bulgaria', 2019, 7312912),
 ('Bulgaria', 2020, 7062590),
 ('Bulgaria', 2021, 7035214),
 ('Bulgaria', None, 21410716),
 ('Canada', 2019, 7158271),
 ('Canada', 2020, 7096597),
 ('Canada', 2021, 7320570),
 ('Canada', None, 21575438),
 ('Cyprus', 2019, 7250287),
 ('Cyprus', 2020, 7160571),
 ('Cyprus', 2021, 7089668),
 ('Cyprus', None, 21500526),
 ('Czech Republic', 2019, 7087032),
 ('Czech Republic', 2020, 7109774),
 ('Czech Republic', 2021, 7137336),
 ('Czech Republic', None, 21334142),
 ('Denmark', 2019, 6955746),
 ('Denmark', 2020, 7151333),
 ('Denmark', 2021, 7224018),
 ('Denmark', None, 21331097),
 ('Egypt', 2019, 7169300),
 ('Egypt', 2020, 7168510),
 ('Egypt', 2021, 7042157),
 ('Egypt', None, 21379967),
 ('Estonia', 2019, 7193792),
 ('Estonia', 2020, 7153968),
 ('Estonia', 2021, 7145294),
 ('Estonia', None, 21493054),
 ('Finland', 2019, 7064381),
 ('Finland', 2020, 7273293),
 ('Finland', 2021, 6998514),
 ('Finland', None, 21336188),
 ('France', 2019, 7077076),
 ('France', 2020, 7148684),
 ('France', 2021, 7115295),
 ('France', None, 21341055),
 ('Germany', 2019, 7056510),
 ('Germany', 2020, 7130416),
 ('Germany', 2021, 7115005),
 ('Germany', None, 21301931),
 ('Greece', 2019, 7208571),
 ('Greece', 2020, 7088420),
 ('Greece', 2021, 7115402),
 ('Greece', None, 21412393),
 ('Hungary', 2019, 6922795),
 ('Hungary', 2020, 7268115),
 ('Hungary', 2021, 7147105),
 ('Hungary', None, 21338015),
 ('India', 2019, 7210119),
 ('India', 2020, 7007938),
 ('India', 2021, 7112826),
 ('India', None, 21330883),
 ('Indonesia', 2019, 7316521),
 ('Indonesia', 2020, 7120300),
 ('Indonesia', 2021, 7062139),
 ('Indonesia', None, 21498960),
 ('Ireland', 2019, 6886406),
 ('Ireland', 2020, 7169915),
 ('Ireland', 2021, 7039661),
 ('Ireland', None, 21095982),
 ('Israel', 2019, 7158364),
 ('Israel', 2020, 7131641),
 ('Israel', 2021, 7291543),
 ('Israel', None, 21581548),
 ('Italy', 2019, 7310397),
 ('Italy', 2020, 7205021),
 ('Italy', 2021, 7329495),
 ('Italy', None, 21844913),
 ('Japan', 2019, 7171888),
 ('Japan', 2020, 7243424),
 ('Japan', 2021, 7350029),
 ('Japan', None, 21765341),
 ('Jordan', 2019, 7050643),
 ('Jordan', 2020, 7406677),
 ('Jordan', 2021, 6972284),
 ('Jordan', None, 21429604),
 ('Malaysia', 2019, 7210717),
 ('Malaysia', 2020, 7134332),
 ('Malaysia', 2021, 7107548),
 ('Malaysia', None, 21452597),
 ('Mexico', 2019, 7139099),
 ('Mexico', 2020, 7274694),
 ('Mexico', 2021, 7041611),
 ('Mexico', None, 21455404),
 ('Netherlands', 2019, 7024290),
 ('Netherlands', 2020, 7184262),
 ('Netherlands', 2021, 7174467),
 ('Netherlands', None, 21383019),
 ('New Zealand', 2019, 7104151),
 ('New Zealand', 2020, 7148210),
 ('New Zealand', 2021, 7077100),
 ('New Zealand', None, 21329461),
 ('Norway', 2019, 7226127),
 ('Norway', 2020, 7195402),
 ('Norway', 2021, 7122910),
 ('Norway', None, 21544439),
 ('Oman', 2019, 7002176),
 ('Oman', 2020, 7203070),
 ('Oman', 2021, 7227875),
 ('Oman', None, 21433121),
 ('Peru', 2019, 7175741),
 ('Peru', 2020, 7173865),
 ('Peru', 2021, 7354856),
 ('Peru', None, 21704462),
 ('Philippines', 2019, 7168433),
 ('Philippines', 2020, 7266549),
 ('Philippines', 2021, 7216780),
 ('Philippines', None, 21651762),
 ('Poland', 2019, 7177702),
 ('Poland', 2020, 7287128),
 ('Poland', 2021, 7380301),
 ('Poland', None, 21845131),
 ('Portugal', 2019, 7191396),
 ('Portugal', 2020, 7063270),
 ('Portugal', 2021, 7299945),
 ('Portugal', None, 21554611),
 ('Qatar', 2019, 7145232),
 ('Qatar', 2020, 7060806),
 ('Qatar', 2021, 7267724),
 ('Qatar', None, 21473762),
 ('Russia', 2019, 7203054),
 ('Russia', 2020, 7229902),
 ('Russia', 2021, 7305920),
 ('Russia', None, 21738876),
 ('Saudi Arabia', 2019, 7232912),
 ('Saudi Arabia', 2020, 6976506),
 ('Saudi Arabia', 2021, 7117019),
 ('Saudi Arabia', None, 21326437),
 ('Singapore', 2019, 7213629),
 ('Singapore', 2020, 7157325),
 ('Singapore', 2021, 7164012),
 ('Singapore', None, 21534966),
 ('South Africa', 2019, 7172267),
 ('South Africa', 2020, 7124154),
 ('South Africa', 2021, 7098334),
 ('South Africa', None, 21394755),
 ('South Korea', 2019, 7200641),
 ('South Korea', 2020, 7173578),
 ('South Korea', 2021, 7224149),
 ('South Korea', None, 21598368),
 ('Spain', 2019, 7176003),
 ('Spain', 2020, 7263889),
 ('Spain', 2021, 7025450),
 ('Spain', None, 21465342),
 ('Sudan', 2019, 7050033),
 ('Sudan', 2020, 7089359),
 ('Sudan', 2021, 7276542),
 ('Sudan', None, 21415934),
 ('Sweden', 2019, 6967624),
 ('Sweden', 2020, 7021102),
 ('Sweden', 2021, 7011799),
 ('Sweden', None, 21000525),
 ('Switzerland', 2019, 7214776),
 ('Switzerland', 2020, 7100075),
 ('Switzerland', 2021, 7211246),
 ('Switzerland', None, 21526097),
 ('Taiwan', 2019, 7061343),
 ('Taiwan', 2020, 6832009),
 ('Taiwan', 2021, 7166856),
 ('Taiwan', None, 21060208),
 ('Tajikistan', 2019, 7108172),
 ('Tajikistan', 2020, 7164570),
 ('Tajikistan', 2021, 7244771),
 ('Tajikistan', None, 21517513),
 ('Thailand', 2019, 7307381),
 ('Thailand', 2020, 7346771),
 ('Thailand', 2021, 7194624),
 ('Thailand', None, 21848776),
 ('Turkey', 2019, 7075035),
 ('Turkey', 2020, 6978646),
 ('Turkey', 2021, 7217056),
 ('Turkey', None, 21270737),
 ('Ukraine', 2019, 7117247),
 ('Ukraine', 2020, 7294426),
 ('Ukraine', 2021, 7063067),
 ('Ukraine', None, 21474740),
 ('United Arab Emirates', 2019, 7249878),
 ('United Arab Emirates', 2020, 7044465),
 ('United Arab Emirates', 2021, 7149878),
 ('United Arab Emirates', None, 21444221),
 ('United Kingdom', 2019, 6984407),
 ('United Kingdom', 2020, 7348129),
 ('United Kingdom', 2021, 7082577),
 ('United Kingdom', None, 21415113),
 ('United States', 2019, 7019456),
 ('United States', 2020, 7007530),
 ('United States', 2021, 6981011),
 ('United States', None, 21007997),
 ('Uruguay', 2019, 6909425),
 ('Uruguay', 2020, 7282415),
 ('Uruguay', 2021, 7129542),
 ('Uruguay', None, 21321382),
 ('Uzbekistan', 2019, 7225079),
 ('Uzbekistan', 2020, 7125027),
 ('Uzbekistan', 2021, 7065974),
 ('Uzbekistan', None, 21416080),
 ('Vietnam', 2019, 7064760),
 ('Vietnam', 2020, 7079773),
 ('Vietnam', 2021, 7136039),
 ('Vietnam', None, 21280572),
 (None, None, 1201006258)]

##### Create a cube query using the columns year, country, and average sales.

In [24]:
%sql SELECT dimcountry.country,dimdate.year, SUM(factsales.amount) AS totalsales\
    FROM dimcountry\
    INNER JOIN factsales\
    ON dimcountry.country_id = factsales.country_id\
    INNER JOIN dimdate\
    ON dimdate.date_id = factsales.date_id\
    GROUP BY CUBE(dimcountry.country, dimdate.year)\
    ORDER BY dimcountry.country, dimdate.year

 * postgresql://postgres:***@localhost/sales
228 rows affected.

[('Argentina', 2019, 7163167),
 ('Argentina', 2020, 7327655),
 ('Argentina', 2021, 7264759),
 ('Argentina', None, 21755581),
 ('Australia', 2019, 7259016),
 ('Australia', 2020, 6964260),
 ('Australia', 2021, 7298728),
 ('Australia', None, 21522004),
 ('Austria', 2019, 7320233),
 ('Austria', 2020, 7071166),
 ('Austria', 2021, 6974327),
 ('Austria', None, 21365726),
 ('Azerbaijan', 2019, 7097729),
 ('Azerbaijan', 2020, 7191956),
 ('Azerbaijan', 2021, 7036081),
 ('Azerbaijan', None, 21325766),
 ('Belgium', 2019, 7093441),
 ('Belgium', 2020, 7070520),
 ('Belgium', 2021, 7334288),
 ('Belgium', None, 21498249),
 ('Brazil', 2019, 7116253),
 ('Brazil', 2020, 7087658),
 ('Brazil', 2021, 7146860),
 ('Brazil', None, 21350771),
 ('Bulgaria', 2019, 7312912),
 ('Bulgaria', 2020, 7062590),
 ('Bulgaria', 2021, 7035214),
 ('Bulgaria', None, 21410716),
 ('Canada', 2019, 7158271),
 ('Canada', 2020, 7096597),
 ('Canada', 2021, 7320570),
 ('Canada', None, 21575438),
 ('Cyprus', 2019, 7250287),
 ('Cyprus', 2020, 7160571),
 ('Cyprus', 2021, 7089668),
 ('Cyprus', None, 21500526),
 ('Czech Republic', 2019, 7087032),
 ('Czech Republic', 2020, 7109774),
 ('Czech Republic', 2021, 7137336),
 ('Czech Republic', None, 21334142),
 ('Denmark', 2019, 6955746),
 ('Denmark', 2020, 7151333),
 ('Denmark', 2021, 7224018),
 ('Denmark', None, 21331097),
 ('Egypt', 2019, 7169300),
 ('Egypt', 2020, 7168510),
 ('Egypt', 2021, 7042157),
 ('Egypt', None, 21379967),
 ('Estonia', 2019, 7193792),
 ('Estonia', 2020, 7153968),
 ('Estonia', 2021, 7145294),
 ('Estonia', None, 21493054),
 ('Finland', 2019, 7064381),
 ('Finland', 2020, 7273293),
 ('Finland', 2021, 6998514),
 ('Finland', None, 21336188),
 ('France', 2019, 7077076),
 ('France', 2020, 7148684),
 ('France', 2021, 7115295),
 ('France', None, 21341055),
 ('Germany', 2019, 7056510),
 ('Germany', 2020, 7130416),
 ('Germany', 2021, 7115005),
 ('Germany', None, 21301931),
 ('Greece', 2019, 7208571),
 ('Greece', 2020, 7088420),
 ('Greece', 2021, 7115402),
 ('Greece', None, 21412393),
 ('Hungary', 2019, 6922795),
 ('Hungary', 2020, 7268115),
 ('Hungary', 2021, 7147105),
 ('Hungary', None, 21338015),
 ('India', 2019, 7210119),
 ('India', 2020, 7007938),
 ('India', 2021, 7112826),
 ('India', None, 21330883),
 ('Indonesia', 2019, 7316521),
 ('Indonesia', 2020, 7120300),
 ('Indonesia', 2021, 7062139),
 ('Indonesia', None, 21498960),
 ('Ireland', 2019, 6886406),
 ('Ireland', 2020, 7169915),
 ('Ireland', 2021, 7039661),
 ('Ireland', None, 21095982),
 ('Israel', 2019, 7158364),
 ('Israel', 2020, 7131641),
 ('Israel', 2021, 7291543),
 ('Israel', None, 21581548),
 ('Italy', 2019, 7310397),
 ('Italy', 2020, 7205021),
 ('Italy', 2021, 7329495),
 ('Italy', None, 21844913),
 ('Japan', 2019, 7171888),
 ('Japan', 2020, 7243424),
 ('Japan', 2021, 7350029),
 ('Japan', None, 21765341),
 ('Jordan', 2019, 7050643),
 ('Jordan', 2020, 7406677),
 ('Jordan', 2021, 6972284),
 ('Jordan', None, 21429604),
 ('Malaysia', 2019, 7210717),
 ('Malaysia', 2020, 7134332),
 ('Malaysia', 2021, 7107548),
 ('Malaysia', None, 21452597),
 ('Mexico', 2019, 7139099),
 ('Mexico', 2020, 7274694),
 ('Mexico', 2021, 7041611),
 ('Mexico', None, 21455404),
 ('Netherlands', 2019, 7024290),
 ('Netherlands', 2020, 7184262),
 ('Netherlands', 2021, 7174467),
 ('Netherlands', None, 21383019),
 ('New Zealand', 2019, 7104151),
 ('New Zealand', 2020, 7148210),
 ('New Zealand', 2021, 7077100),
 ('New Zealand', None, 21329461),
 ('Norway', 2019, 7226127),
 ('Norway', 2020, 7195402),
 ('Norway', 2021, 7122910),
 ('Norway', None, 21544439),
 ('Oman', 2019, 7002176),
 ('Oman', 2020, 7203070),
 ('Oman', 2021, 7227875),
 ('Oman', None, 21433121),
 ('Peru', 2019, 7175741),
 ('Peru', 2020, 7173865),
 ('Peru', 2021, 7354856),
 ('Peru', None, 21704462),
 ('Philippines', 2019, 7168433),
 ('Philippines', 2020, 7266549),
 ('Philippines', 2021, 7216780),
 ('Philippines', None, 21651762),
 ('Poland', 2019, 7177702),
 ('Poland', 2020, 7287128),
 ('Poland', 2021, 7380301),
 ('Poland', None, 21845131),
 ('Portugal', 2019, 7191396),
 ('Portugal', 2020, 7063270),
 ('Portugal', 2021, 7299945),
 ('Portugal', None, 21554611),
 ('Qatar', 2019, 7145232),
 ('Qatar', 2020, 7060806),
 ('Qatar', 2021, 7267724),
 ('Qatar', None, 21473762),
 ('Russia', 2019, 7203054),
 ('Russia', 2020, 7229902),
 ('Russia', 2021, 7305920),
 ('Russia', None, 21738876),
 ('Saudi Arabia', 2019, 7232912),
 ('Saudi Arabia', 2020, 6976506),
 ('Saudi Arabia', 2021, 7117019),
 ('Saudi Arabia', None, 21326437),
 ('Singapore', 2019, 7213629),
 ('Singapore', 2020, 7157325),
 ('Singapore', 2021, 7164012),
 ('Singapore', None, 21534966),
 ('South Africa', 2019, 7172267),
 ('South Africa', 2020, 7124154),
 ('South Africa', 2021, 7098334),
 ('South Africa', None, 21394755),
 ('South Korea', 2019, 7200641),
 ('South Korea', 2020, 7173578),
 ('South Korea', 2021, 7224149),
 ('South Korea', None, 21598368),
 ('Spain', 2019, 7176003),
 ('Spain', 2020, 7263889),
 ('Spain', 2021, 7025450),
 ('Spain', None, 21465342),
 ('Sudan', 2019, 7050033),
 ('Sudan', 2020, 7089359),
 ('Sudan', 2021, 7276542),
 ('Sudan', None, 21415934),
 ('Sweden', 2019, 6967624),
 ('Sweden', 2020, 7021102),
 ('Sweden', 2021, 7011799),
 ('Sweden', None, 21000525),
 ('Switzerland', 2019, 7214776),
 ('Switzerland', 2020, 7100075),
 ('Switzerland', 2021, 7211246),
 ('Switzerland', None, 21526097),
 ('Taiwan', 2019, 7061343),
 ('Taiwan', 2020, 6832009),
 ('Taiwan', 2021, 7166856),
 ('Taiwan', None, 21060208),
 ('Tajikistan', 2019, 7108172),
 ('Tajikistan', 2020, 7164570),
 ('Tajikistan', 2021, 7244771),
 ('Tajikistan', None, 21517513),
 ('Thailand', 2019, 7307381),
 ('Thailand', 2020, 7346771),
 ('Thailand', 2021, 7194624),
 ('Thailand', None, 21848776),
 ('Turkey', 2019, 7075035),
 ('Turkey', 2020, 6978646),
 ('Turkey', 2021, 7217056),
 ('Turkey', None, 21270737),
 ('Ukraine', 2019, 7117247),
 ('Ukraine', 2020, 7294426),
 ('Ukraine', 2021, 7063067),
 ('Ukraine', None, 21474740),
 ('United Arab Emirates', 2019, 7249878),
 ('United Arab Emirates', 2020, 7044465),
 ('United Arab Emirates', 2021, 7149878),
 ('United Arab Emirates', None, 21444221),
 ('United Kingdom', 2019, 6984407),
 ('United Kingdom', 2020, 7348129),
 ('United Kingdom', 2021, 7082577),
 ('United Kingdom', None, 21415113),
 ('United States', 2019, 7019456),
 ('United States', 2020, 7007530),
 ('United States', 2021, 6981011),
 ('United States', None, 21007997),
 ('Uruguay', 2019, 6909425),
 ('Uruguay', 2020, 7282415),
 ('Uruguay', 2021, 7129542),
 ('Uruguay', None, 21321382),
 ('Uzbekistan', 2019, 7225079),
 ('Uzbekistan', 2020, 7125027),
 ('Uzbekistan', 2021, 7065974),
 ('Uzbekistan', None, 21416080),
 ('Vietnam', 2019, 7064760),
 ('Vietnam', 2020, 7079773),
 ('Vietnam', 2021, 7136039),
 ('Vietnam', None, 21280572),
 (None, 2019, 399729036),
 (None, 2020, 400441641),
 (None, 2021, 400835581),
 (None, None, 1201006258)]

##### Create a Materialized Query Table(MQT). Create an MQT named total_sales_per_country that has the columns country and total_sales.

In [28]:
%sql CREATE TABLE total_sales_per_country (country, total_sales) AS\
    (SELECT dimcountry.country, sum(amount) FROM factsales INNER JOIN dimcountry\
    ON dimcountry.country_id = factsales.country_id\
    GROUP BY country)

 * postgresql://postgres:***@localhost/sales
56 rows affected.

[]

In [29]:
%sql SELECT * FROM total_sales_per_country LIMIT 5;

 * postgresql://postgres:***@localhost/sales
5 rows affected.

[('Argentina', 21755581),
 ('Australia', 21522004),
 ('Austria', 21365726),
 ('Azerbaijan', 21325766),
 ('Belgium', 21498249)]